import Head from 'next/head';
import { ToastContainer } from 'react-toastify';
import AppProvider from '../utils/context';
import { basePath } from '../services/constants';
import type { AppProps } from 'next/app';

import 'react-toastify/dist/ReactToastify.css';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Template Webview</title>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover"
        />
        <meta name="description" content="Generated by Lila Software Studio" />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </Head>
      <AppProvider>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <Component {...pageProps} />
      </AppProvider>
    </>
  );
}

export default MyApp;
